version: "3"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/db


volumes:
  redis_data:
  redisinsight_data:
